apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker1
  template:
    metadata:
      labels:
        app: docker1
    spec:
      containers:
      - name: docker1-container
        image: vanditak11/docker-1:latest
        ports:
        - containerPort: 80


